# Dashboard/dashboard_data_service.py
#
# AWS mode  : reads unique_errors.json + CSV from S3 processed bucket.
# Local mode: reads from Conversion/ directory.
#
# LOG RETENTION (Stories 4968/4970)
# ----------------------------------
# The number of days to retain is set by LOG_RETENTION_DAYS env var.
# Customer can set ANY number — 30, 90, 100, 200, 365 etc.
# No hardcoded list of allowed values.
#
# DASHBOARD DATE FILTER
# ----------------------
# The filter strip sends a 'date' query param (YYYY-MM-DD) meaning:
# "show logs from the retention cutoff UP TO this date."
# The dropdown options are generated by the JS from the retention window.

import csv, io, json, logging, os
from datetime import date, timedelta
from typing import Dict, List, Optional
import boto3

_logger = logging.getLogger(__name__)

STATUS_CODE_KEY = 'Status Code'
ERROR_CODE_KEY  = 'Error Code'
DESCRIPTION_KEY = 'Description'
API_KEY         = 'API'
COUNT_KEY       = 'Count'
LAST_SEEN_KEY   = 'Last Seen'
UNIQUE_ERRORS_JSON_FILENAME        = 'unique_errors.json'
LEGACY_UNIQUE_ERRORS_JSON_FILENAME = 'unique errors.json'

# ── Read env vars dynamically at call time (not at import time) ──────────────
# This is critical: ECS Fargate injects env vars before the process starts,
# but module-level code runs during import which may happen before injection
# in some edge cases. Using functions guarantees the current value is always used.

def _get_processed_bucket() -> str:
    return os.environ.get('PROCESSED_BUCKET', '')

def _get_processed_prefix() -> str:
    return os.environ.get('PROCESSED_LOG_PREFIX',
           os.environ.get('PROCESSED_PREFIX', 'processed/'))

def _get_aws_region() -> str:
    return os.environ.get('AWS_DEFAULT_REGION',
           os.environ.get('AWS_REGION', 'us-east-1'))

def _is_aws() -> bool:
    return bool(os.environ.get('PROCESSED_BUCKET', ''))

# Backward-compat: keep _IS_AWS accessible as a variable for any code that checks it
# But evaluate it lazily via the function — don't cache at import time
_PROCESSED_BUCKET = ''   # placeholder — use _get_processed_bucket() in all code
_PROCESSED_PREFIX = ''   # placeholder — use _get_processed_prefix() in all code
_AWS_REGION       = ''   # placeholder — use _get_aws_region() in all code
_IS_AWS           = False # placeholder — use _is_aws() in all code

# ── Retention configuration ───────────────────────────────────────────────────
# Read once at module load. Any integer accepted — no AllowedValues constraint.
import os as _os
_RETENTION_DAYS = int(_os.environ.get('LOG_RETENTION_DAYS', '90'))


def _retention_cutoff() -> date:
    """Earliest date that is retained (today - LOG_RETENTION_DAYS)."""
    if _RETENTION_DAYS <= 0:
        return date.min
    return date.today() - timedelta(days=_RETENTION_DAYS)


# ── S3 helpers ────────────────────────────────────────────────────────────────

def _s3():
    return boto3.client('s3', region_name=_get_aws_region())

def _s3_get_text(key: str) -> Optional[str]:
    bucket = _get_processed_bucket()
    if not bucket:
        _logger.warning('[dashboard_data] PROCESSED_BUCKET env var not set — '
                        'cannot read from S3. Current env: %s',
                        {k: v for k, v in os.environ.items()
                         if 'BUCKET' in k or 'PROCESSED' in k})
        return None
    try:
        resp    = _s3().get_object(Bucket=bucket, Key=key)
        content = resp['Body'].read().decode('utf-8', errors='replace')
        _logger.info('[dashboard_data] S3 read OK: s3://%s/%s (%d bytes)',
                     bucket, key, len(content))
        return content
    except Exception as exc:
        err_str = str(exc)
        if 'NoSuchKey' in err_str or '404' in err_str:
            _logger.info('[dashboard_data] Key not found: s3://%s/%s', bucket, key)
        else:
            _logger.warning('[dashboard_data] S3 GET s3://%s/%s failed: %s', bucket, key, exc)
        return None

def _s3_json_key() -> str:
    return f"{_get_processed_prefix()}{UNIQUE_ERRORS_JSON_FILENAME}"

def _s3_csv_key() -> str:
    return f"{_get_processed_prefix()}converted_application_logs.csv"


# ── Readers ───────────────────────────────────────────────────────────────────

def _read_unique_errors_data(conversion_dir: str) -> List[dict]:
    _logger.info('[dashboard_data] _read_unique_errors_data: is_aws=%s bucket=%s prefix=%s',
                 _is_aws(), _get_processed_bucket(), _get_processed_prefix())
    if _is_aws():
        text = _s3_get_text(_s3_json_key())
        if text is None:
            return []
        try:
            data = json.loads(text)
            if not isinstance(data, list):
                return []
            # Normalise: handle old 'Status code' (lowercase c) from previous Lambda version
            normalised = []
            for entry in data:
                if 'Status code' in entry and 'Status Code' not in entry:
                    entry = dict(entry)
                    entry['Status Code'] = entry.pop('Status code')
                normalised.append(entry)
            return normalised
        except Exception:
            return []
    for fname in (UNIQUE_ERRORS_JSON_FILENAME, LEGACY_UNIQUE_ERRORS_JSON_FILENAME):
        path = os.path.join(conversion_dir, fname)
        if not os.path.exists(path):
            continue
        try:
            with open(path, 'r', encoding='utf-8') as f:
                data = json.load(f)
                return data if isinstance(data, list) else []
        except Exception:
            continue
    return []


# ── Date filter (new dropdown model) ─────────────────────────────────────────

def _resolve_date_filters(request_args):
    """
    Supports three filter modes, sent by the dashboard:
      preset=today   → today only
      preset=week    → last 7 days
      preset=month   → last 30 days
      preset=all     → full retention window (no extra date cap)
      date=YYYY-MM-DD→ retention cutoff up to this specific date (dropdown)
      (nothing)      → full retention window

    Returns (date_from, date_to, label).
    date_from is always capped at the retention cutoff so data beyond
    the retention window is never returned.
    """
    cutoff = _retention_cutoff()
    today  = date.today()

    # ── From/To calendar inputs (highest priority) ──────────────────────────────
    from_param = request_args.get('from', '').strip()
    to_param   = request_args.get('to',   '').strip()
    if from_param or to_param:
        try:
            df = date.fromisoformat(from_param) if from_param else None
            dt = date.fromisoformat(to_param)   if to_param   else today
            if df and cutoff != date.min: df = max(df, cutoff)
            if df is None and cutoff != date.min: df = cutoff
            dt = min(dt, today)
            fl = df.strftime('%d %b %Y') if df else '...'
            tl = dt.strftime('%d %b %Y')
            return df, dt, f'{fl} → {tl}'
        except ValueError:
            pass

    # ── Dropdown date param (second priority) ─────────────────────────────────
    date_param = request_args.get('date', '').strip()
    if date_param:
        try:
            selected = date.fromisoformat(date_param)
            selected = min(selected, today)
            if cutoff != date.min:
                selected = max(selected, cutoff)
            return (cutoff if cutoff != date.min else None), selected,                    f'Up to {selected.strftime("%d %b %Y")}'
        except ValueError:
            pass

    # ── Preset buttons ────────────────────────────────────────────────────────
    preset = request_args.get('preset', '').strip()

    if preset == 'today':
        df = max(today, cutoff) if cutoff != date.min else today
        return df, today, 'Today'

    if preset == 'week':
        df = max(today - timedelta(days=6), cutoff) if cutoff != date.min              else today - timedelta(days=6)
        return df, today, 'Last 7 Days'

    if preset == 'month':
        df = max(today - timedelta(days=29), cutoff) if cutoff != date.min              else today - timedelta(days=29)
        return df, today, 'Last 30 Days'

    # ── Default / All Time / no filter ────────────────────────────────────────
    if cutoff != date.min:
        return cutoff, today, f'Last {_RETENTION_DAYS} Days'
    return None, None, 'All Time'


# ── Row helpers ───────────────────────────────────────────────────────────────

def _row_is_in_range(row_date: date,
                     date_from: Optional[date],
                     date_to:   Optional[date]) -> bool:
    if date_from and row_date < date_from:
        return False
    if date_to   and row_date > date_to:
        return False
    return True


def _update_aggregated_error(aggregated, row,
                              row_date_str: str,
                              row_timestamp_str: str):
    # Use .get() with fallback to handle both old 'Status code' and new 'Status Code'
    sc_val = row.get('Status Code') or row.get('Status code', '')
    key = (sc_val, row.get(ERROR_CODE_KEY, ''),
           row.get(DESCRIPTION_KEY, ''), row.get(API_KEY, ''))
    if key not in aggregated:
        aggregated[key] = {'count': 0, 'dates': set(), 'last_seen': ''}
    aggregated[key]['count'] += 1
    if row_date_str:
        cutoff_s = _retention_cutoff().isoformat()
        if _RETENTION_DAYS <= 0 or row_date_str >= cutoff_s:
            aggregated[key]['dates'].add(row_date_str)
    if row_timestamp_str and row_timestamp_str > aggregated[key]['last_seen']:
        aggregated[key]['last_seen'] = row_timestamp_str
    elif row_date_str and row_date_str > aggregated[key]['last_seen']:
        aggregated[key]['last_seen'] = row_date_str


def _serialize_aggregated_errors(aggregated):
    return [
        {STATUS_CODE_KEY: k[0], ERROR_CODE_KEY: k[1],
         DESCRIPTION_KEY: k[2], API_KEY: k[3],
         COUNT_KEY: m['count'], LAST_SEEN_KEY: m['last_seen'],
         'Dates': sorted(m['dates'])}
        for k, m in sorted(aggregated.items())
        if k[0] and k[0].isdigit() and int(k[0]) >= 400 and k[1]
    ]


# ── Main collector ────────────────────────────────────────────────────────────

def _collect_unique_errors(conversion_dir, date_from, date_to):
    """Read errors and apply retention + date filter."""
    if not (date_from or date_to):
        # No filter — read JSON directly, still apply retention
        raw = _read_unique_errors_data(conversion_dir)
        if _RETENTION_DAYS <= 0:
            return raw
        cutoff_s = _retention_cutoff().isoformat()
        filtered = []
        for entry in raw:
            last_seen = entry.get(LAST_SEEN_KEY, '')
            # Only skip entries where last_seen is set AND older than cutoff
            # Empty last_seen means it's a new/unprocessed entry — keep it
            if last_seen and len(last_seen) >= 10 and last_seen[:10] < cutoff_s:
                continue
            entry = dict(entry)
            entry['Dates'] = [d for d in entry.get('Dates', []) if d >= cutoff_s]
            filtered.append(entry)
        return filtered

    # Date range — read CSV and reaggregate
    if _is_aws():
        csv_text = _s3_get_text(_s3_csv_key())
        if csv_text is None:
            return _collect_unique_errors(conversion_dir, None, None)
        reader = csv.DictReader(io.StringIO(csv_text))
    else:
        csv_path = os.path.join(conversion_dir, 'converted_application_logs.csv')
        if not os.path.exists(csv_path):
            return _collect_unique_errors(conversion_dir, None, None)
        reader = csv.DictReader(open(csv_path, 'r', encoding='utf-8'))

    aggregated = {}
    for row in reader:
        row_date_str      = row.get('Date', '')
        row_timestamp_str = row.get('Timestamp', '')
        try:
            row_date = date.fromisoformat(row_date_str)
        except ValueError:
            continue
        if not _row_is_in_range(row_date, date_from, date_to):
            continue
        # Normalise 'Status code' → 'Status Code' for older CSV files
        if 'Status code' in row and 'Status Code' not in row:
            row['Status Code'] = row.pop('Status code')
        _update_aggregated_error(aggregated, row, row_date_str, row_timestamp_str)

    return _serialize_aggregated_errors(aggregated)


# ── Public API ────────────────────────────────────────────────────────────────

def build_dashboard_payload(conversion_dir, run_conversion_outputs, request_args):
    """Build the full dashboard JSON payload."""
    # Log current mode to CloudWatch for debugging
    _logger.info('[dashboard_data] build_dashboard_payload: is_aws=%s bucket=%s',
                 _is_aws(), _get_processed_bucket() or 'NOT SET')
    if not _is_aws():
        run_conversion_outputs()

    date_from, date_to, filter_label = _resolve_date_filters(request_args)
    unique_errors = _collect_unique_errors(conversion_dir, date_from, date_to)

    total_errors = sum(item.get(COUNT_KEY, 0) for item in unique_errors)
    by_status, by_api = {}, {}
    for item in unique_errors:
        sc  = str(item.get(STATUS_CODE_KEY, 'Unknown'))
        api = str(item.get(API_KEY, 'Unknown'))
        cnt = int(item.get(COUNT_KEY, 0))
        by_status[sc]  = by_status.get(sc, 0)  + cnt
        by_api[api]    = by_api.get(api, 0)     + cnt

    cutoff = _retention_cutoff()
    return {
        'summary': {
            'uniqueErrorTypes': len(unique_errors),
            'totalErrorEvents': total_errors,
            'statusCodeCount':  len(by_status),
            'apiCount':         len(by_api),
            'source':           'aws-s3' if _is_aws() else 'local',
        },
        'byStatus': by_status,
        'byApi':    by_api,
        'rows':     unique_errors,
        'filter': {
            'date':          date_to.isoformat()   if date_to   else None,
            'from':          date_from.isoformat() if date_from else None,
            'to':            date_to.isoformat()   if date_to   else None,
            'label':         filter_label,
            'retentionDays': _RETENTION_DAYS,
            'cutoffDate':    cutoff.isoformat() if cutoff != date.min else None,
            'today':         date.today().isoformat(),
        },
    }
